config/routes.rb
Seat::Application.routes.draw do
  resources :chats

  resources :charts

  resource :users
  resource :session
  match '/register' => "users#new", :as => "register"
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
  match '/:id' => "charts#index" 
  root :to => "charts#index", :as => "root"

end

app/models/chart.rb
class Chart < ActiveRecord::Base
	validates :user_id, :uniqueness => { :scope => [:user_id, :seat] }

	has_many :user, :order => 'seat ASC'

	attr_accessor :username
	attr_accessor :active
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  # GET /charts
  # GET /charts.xml
  def index
    #Find a seat that someone clicked on in the chart
    #only if they are logged in
    if params[:id] != nil && session[:user_id] != nil
         @seat = Chart.first(:conditions => {:seat=>params[:id]})

         # Check that the seat is empty
         if @seat.user_id == nil && @seat.id != nil
	     # The seat is empty, add this user to it
            # but first remove the user from any other seat
            Chart.update_all({:user_id => nil}, {:user_id => session[:user_id]})
            Chart.update(params[:id], {:user_id => session[:user_id]})

            # Display success message
            flash.now[:success] = "You are now sitting in seat #{params[:id]}!"
         elsif @seat.user_id == session[:user_id]
            # The user is already is that seat, so remove them
            Chart.update(params[:id], {:user_id => nil})
            flash.now[:success] = "You are no longer sitting in seat #{params[:id]}!"
         else
            # Display error message, seat taken
            flash.now[:error] = "Sorry, but that seat is currently occupied."
         end
    end

    # Get all seats in the chart
    @charts = Chart.find(:all, :order => "seat ASC")
    @charts.each_with_index do |seat, index|
	if seat.user_id != nil
		@charts[index].username = User.first(:conditions => {:id=>seat.user_id}).username
 		
		@chats = Chat.find_by_username(@charts[index].username, :conditions => ["created_at >= ?", Time.now().utc - 5.minutes])
      		if @chats != nil
           		@charts[index].active = true;
       	else
          		@charts[index].active = false;
       	end
	end
    end

    respond_to do |format|
      format.html # index.html.erb
      #format.xml  { render :xml => @charts }
      format.js
    end
  end

  # GET /charts/1
  # GET /charts/1.xml
  def show
    @chart = Chart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @chart }
    end
  end

  # GET /charts/new
  # GET /charts/new.xml
  def new
    @chart = Chart.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @chart }
    end
  end

  # GET /charts/1/edit
  def edit
    @chart = Chart.find(params[:id])
  end

  # POST /charts
  # POST /charts.xml
  def create
    @chart = Chart.new(params[:chart])

    respond_to do |format|
      if @chart.save
        format.html { redirect_to(@chart, :notice => 'Chart was successfully created.') }
        format.xml  { render :xml => @chart, :status => :created, :location => @chart }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @chart.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /charts/1
  # PUT /charts/1.xml
  def update
    @chart = Chart.find(params[:id])

    respond_to do |format|
      if @chart.update_attributes(params[:chart])
        format.html { redirect_to(@chart, :notice => 'Chart was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @chart.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /charts/1
  # DELETE /charts/1.xml
  def destroy
    @chart = Chart.find(params[:id])
    @chart.destroy

    respond_to do |format|
      format.html { redirect_to(charts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/views/charts/_form.html.erb
<%= form_for(@chart) do |f| %>
  <% if @chart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chart.errors.count, "error") %> prohibited this chart from being saved:</h2>

      <ul>
      <% @chart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :seat %><br />
    <%= f.text_field :seat %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/charts/edit.html.erb
<h1>Editing chart</h1>

<%= render 'form' %>

<%= link_to 'Show', @chart %> |
<%= link_to 'Back', charts_path %>

app/views/charts/index.html.erb
<div id="container">
	<h1>Seating chart</h1>
	<p>
		<%= link_to "Logout", logout_path unless !session[:user_id]%>
		<%= link_to "Login", login_path unless session[:user_id]%>
		<%= link_to "Register", register_path unless session[:user_id]%>
		<br />
		<%= link_to "Chatting room", chats_path unless !session[:user_id]%>
	</p>
	<h3>Click a seat to change to it!</h3>
	<div id="chart">
	<% align = "right" %>
	<% @charts.each_with_index do |chart, index| %>
		<% if index%4 == 0 %>
		<% if index != 0 %>
		</div>
		<% end %>
			<% if align == "left" %>
			<% align = "right" %>
			<% elsif align = "left" %>
			<% end %>
		<div class="row" style="float:<%=align%>">
		<% end %>
		<a href="<%= root_path + chart.seat.to_s%>" id="<%= chart.seat.to_s%>" class="seat" onclick="">
			<p>
				Seat: <%=chart.seat%><br />
				User: <span class="username"><%=chart.username%></span>
			</p>
			<% if chart.active%>
			<p style="color:#aa0000;">
				Active in Chat!
			</p>
			<% end %>
		</a>
	<% end %>
	</div>
<div style="clear:both;"></div>

<script type="text/javascript">
	$(document).ready(function() {  
		$('a.seat').live({
			click: function(event) {
				event.preventDefault();
	
				$.ajax({
					url: "<%= root_path%>" + $(this).attr('id'),
					data: ({ remote: "true"}),
					cache: false,
					datatype: "xml",
					success: function(data) {
						$('#chart').html($(data).find('#chart').html());
						var success = $(data).find('#flash-success');
						var error = $(data).find('#flash-error');
						
						if ($('div .message').length === 0)
							$('#message').append('<div id="messages"></div>');
						
						if (success.length > 0)
							$('#messages').html($(data).find('#flash-success').html());
						else if (error.length > 0)
							$('#messages').html($(data).find('#flash-error').html());

						if ($('#flash-error').length > 0) {
							alert("truetrue");
							$('#chart').prepend($('#flash-error').html());
						}
					}
				});
			}
		});
	});
</script>

app/views/charts/new.html.erb
<h1>New chart</h1>

<%= render 'form' %>

<%= link_to 'Back', charts_path %>

app/views/charts/show.html.erb
<p id="notice"><%= notice %></p>

<p>Seating Chart</p>

<p>
   <b>User ID:</b>
   <%= @chart.user_id %>
</p>
<p>
   <b>Seat:</b>
   <%= @chart.seat %>
</p>

<%= link_to 'Edit', edit_chart_path(@chart) %> |
<%= link_to 'Back', charts_path %>