config/routes.rb
Seat::Application.routes.draw do
  resources :chats

  resources :charts

  resource :users
  resource :session
  match '/register' => "users#new", :as => "register"
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
  match '/:id' => "charts#index" 
  root :to => "charts#index", :as => "root"

end

app/models/chat.rb
class Chat < ActiveRecord::Base
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  # GET /chats
  # GET /chats.xml
  def index
    @username  = User.first(:conditions => {:id=>session[:user_id]}).username
    @chats = Chat.all.last(60)
    @chat = Chat.new(:username => @username )

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @chats }
    end
  end

  # GET /chats/1
  # GET /chats/1.xml
  def show
    @chat = Chat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @chat }
    end
  end

  # GET /chats/new
  # GET /chats/new.xml
  def new
    @chat = Chat.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @chat }
    end
  end

  # GET /chats/1/edit
  def edit
    @chat = Chat.find(params[:id])
  end

  # POST /chats
  # POST /chats.xml
  def create
    @chat = Chat.new(params[:chat])
      if @chat.save
	respond_to do |format|
        format.html { redirect_to(chats_path) }
	 format.js 
	end
      else
	respond_to do |format|
        format.html { render :action => "new" }
        format.js {render :js => "alert('Error!');"}
	end
      end
  end

  # PUT /chats/1
  # PUT /chats/1.xml
  def update
    @chat = Chat.find(params[:id])

    respond_to do |format|
      if @chat.update_attributes(params[:chat])
        format.html { redirect_to(@chat, :notice => 'Chat was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @chat.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /chats/1
  # DELETE /chats/1.xml
  def destroy
    @chat = Chat.find(params[:id])
    @chat.destroy

    respond_to do |format|
      format.html { redirect_to(chats_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_form.html.erb
<%= form_for(@chat, :remote => true) do |f| %>
<div id="new_chat">
  <div class="field">
      <%= f.hidden_field :username %>
  </div>

  <div class="field">
    <%= f.label :message %>
    <%= f.text_field :message %>
    <%= f.submit :"Send"%>
  </div>
	
</div>
<% end %>

app/views/chats/create.js.erb
$('#chat').append( "<p style=\"padding:4px; margin:0;\"><span style=\"color:#0071ff;\"><%= escape_javascript(@chat.username == "" ? "<Anonymous>" : @chat.username)%></span>:<%=@chat.message%></p>");

$('#new_chat')[0].reset();

$(document).ready(function() {
	setScrollBar();
});

$('form').live({
	submit: function(event){
		event.preventDefault();
		setScrollBar();
	}
});


function setScrollBar() {
	//$('#chat').scrollTop = $('#chat').scrollHeight;
	document.getElementById("chat").scrollTop = document.getElementById("chat").scrollHeight;
}

app/views/chats/edit.html.erb
<h1>Editing chat</h1>

<%= render 'form' %>

<%= link_to 'Show', @chat %> |
<%= link_to 'Back', chats_path %>

app/views/chats/index.html.erb
<h1>On going chats   </h1>
<%= link_to 'Back to Seating Chart', charts_path %>
<% if session[:user_id] != nil %>
	<p>Welcome <%= @username %>!</p>
<% else %>
	<p>Welcome! You may post messages anonymously.</p>

<% end %>

<div style="width:600px; max-height:404px; min-height:20px; border:1px solid #000; overflow:auto;" id="chat">
	<% if @chats.length > 0 %>
		<% @chats.each_with_index do |chat, index|%>
		<p style="padding:4px; margin:0;">
			<span style="color:#0071ff;"><%= (chat.username == "" ? "<Anonymous>" : chat.username)%></span>: 
			<%=chat.message%>
		</p>
		<% end %>

	<% else %>
		<p>There are no messages.</p>
	<% end %>
</div>

<script type="text/javascript">
	window.onload=function() {
		document.getElementById("chat").scrollTop = document.getElementById("chat").scrollHeight;
	}
</script>
<% if false %>
<table>
  <tr>
    <th>Username</th>
    <th>Message</th>
    <th>Time</th>
  </tr>

<% @chats.each do |chat| %>
  <tr>
    <td><%= (chat.username == nil ? "Anonymous" : chat.username) %></td>
    <td><%= chat.message %></td>
         <td><%= chat.created_at %></td>
  </tr>
<% end %>
</table>
<% end %>

<br />
<%= render 'form' %>

app/views/chats/new.html.erb
<h1>New chat</h1>

<%= render 'form' %>

<%= link_to 'Back', chats_path %>

app/views/chats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @chat.username %>
</p>

<p>
  <b>Message:</b>
  <%= @chat.message %>
</p>


<%= link_to 'Edit', edit_chat_path(@chat) %> |
<%= link_to 'Back', chats_path %>